export const TEXT = {
  welcome: {
    title: 'Welcome to FitTrack',
    subtitle: 'The best UI kit for your next health and fitness project',
    getStarted: 'Get Started',
    loginPrompt: 'Already have an account?',
    login: 'Log in',
  },
  login: {
    emailPlaceholder: 'Email Address',
    passwordPlaceholder: 'Password',
    forgotPassword: 'Forgot Password?',
    signInWith: 'Sign in with',
    signIn: 'Sign In',
  },
  forgotPassword: {
    title: 'Reset Your Password',
    subtitle: "Enter your email address below. We'll send you a link to reset your password.",
    label: 'Email Address',
    placeholder: 'Enter your email',
    resetButton: 'Reset Password',
    rememberText: 'Remember your password? Log in',
  },
  signup: {
    title: 'Create Account',
    subtitle: 'Sign up to get started with FitTrack',
    namePlaceholder: 'Your full name',
    emailPlaceholder: 'Email Address',
    passwordPlaceholder: 'Password',
    confirmPasswordPlaceholder: 'Confirm Password',
    button: 'Sign Up',
    loginRedirect: 'Already have an account? Log in',
  },
  emailVerification: {
    title: {
    verified: 'Verify Your Email',
    enter: 'What is your Email address?',
    },
    placeholder: 'Enter your email address',
    verifyButton: 'Verify Email',
    continueButton: 'Continue',
  },
  passwordSetup: {
    title: "Now let's set up your password",
    placeholder: "Enter your password",
    button: "Continue",
    requirements: {
    minLength: "8+ characters",
    upperCase: "At least 1 uppercase",
    number: "At least 1 number",
    },
  },
  onboarding: {
    setName: {
      title: "What’s your name?",
      firstNamePlaceholder: "First Name",
      lastNamePlaceholder: "Last Name",
    },
    setMetrics: {
      title: "Please enter your height and weight.",
      heightPlaceholder: "Height (cm)",
      weightPlaceholder: "Weight (kg)",
    },
    faceId: {
      title: "Enable Face ID",
      subtitle: "If you enable Face ID, you don’t need to enter your password when you login.",
      continueButton: "Continue",
      notNowButton: "Not Now",
    },
    setProfile: {
      title: "Profile Picture",
      subtitle: "You can select photo from one of this emoji or add your own photo as profile picture",
      addPhoto: "Add Custom Photo",
      continue: "Continue",
      viewImage: "View Image",
      modalTitle: "Preview Custom Image",
      modalPlaceholder: "No Image Selected",
      modalCancel: "Cancel",
      modalConfirm: "Confirm",
    },
    setGoals: {
      title: "Let us know how we can help you",
      subtitle: "You can always change this later",
      continue: "Continue",
    },
    setInterests: {
      title: "Time to customize your interests",
      continue: "Continue",
    },
    setGender: {
      title: "Which one are you?",
      subtitle: "To give you a better experience we need to know your gender",
      continue: "Continue",
    },
    readyToGo: {
      title: 'You are ready to go!',
      subTitle: 'Thanks for taking your time to create account with us. Now this is the fun part, let’s explore the app.' 
    }
  },
  home: {
    greeting: "Greetings",
    subtitle: "Eat the right amount of food and stay hydrated through the day",
    moreDetails: "More Details",
    nutrition: "Nutrition",
    nutritionWarning: "Warning",
    nutritionCompleted: "Completed",
    water: "Water",
    waterWarning: "Warning",
    waterCompleted: "Completed",
    dailySteps: "Daily Steps",
    toggle: "On",
  },
  moreDetails: {
    back: 'Back',
    title: 'Monthly Progress',
    totalSteps: 'Total Steps',
    totalCalories: 'Total Calories',
    totalWater: 'Total Water (L)',
    steps: 'Steps',
    calories: 'Nutrition',
    water: 'Water',
    noData: 'No data available for this month.',
    tapToSee: 'Tap a bar to see details',
    dailyBreakdown: 'Daily Breakdown',
    stats: 'Stats',
  },
  nutrition: {
    back: 'Back',
    title: 'You consumed',
    caloriesToday: 'calories today',
    fat: 'Fat',
    carbs: 'Carbs',
    protein: 'Protein',
    deleteMealTitle: 'Confirm Deletion',
    deleteMealMessage: 'Are you sure you want to delete this meal?',
    cancel: 'Cancel',
    ok: 'OK',
    calories: 'Calories',
    addFood: 'Add',
    chooseFoodTitle: 'Choose Food',
    chooseFoodSubtitle: 'Select your meal and your foods that you consume today',
    searchPlaceholder: 'Search',
    noResults: (query: string) => `No record found for "${query}".`,
    close: '✕',
  },
  water: {
    back: 'Back',
    title: 'You drank', 
    glassesToday: 'glasses',
    plusSign: '+', 
    waterDrank: 'Water Drank',
    dailyGoal: 'Daily goal',
    warning: 'You didn’t drink enough water for today.', 
    water: 'Water', 
    waterWarning: 'Warning', 
    waterCompleted: 'Completed', 
  },
  dailySteps: {
    back: 'Back',
    title: 'You walked',
    stepsToday: 'steps today',
    ofDailyGoal: 'of daily goal',
    calBurned: 'Cal Burned',
    dailyGoal: 'Daily goal',
    statistic: 'Statistic',
    close: '✕',
    goalAchieved: 'Goal Achieved!',
    goalIncomplete: 'Goal Incomplete!',
    shareWithFriends: 'Share with friends!',
    stepsLeft: (stepsRemaining: number) => `Just ${stepsRemaining} steps left`,
    shareToFriend: 'Share to friend',
    notNow: 'Not now',
    dailySteps: 'Daily Steps', 
    toggle: 'On',
  },
  userInfo: {
    back: 'Back',
    userNamePlaceholder: 'User Name',
    goals: 'Goals',
    noGoals: 'No goals specified.',
    interests: 'Interests',
    noInterests: 'No interests specified.',
    gender: 'Gender',
    notSpecified: 'Not specified',
  },
  post: {
    back: 'Back',
    userPlaceholder: 'User',
    comments: 'Comments',
    writeComment: 'Write comment...',
    postButton: 'Post',
  },
  notifications: {
    title: 'Notifications',
    enableNotifications: 'Enable Notifications to receive updates about likes, comments, and more.',
    noNotifications: 'No notifications available.',
  },
  settings: {
    title: 'Settings',
    editProfile: 'Edit Profile',
    inviteFriend: 'Invite Friend',
    pushNotification: 'Push Notification',
    enableBiometric: 'Enable Biometric',
    darkMode: 'Dark Mode',
    giveFeedback: 'Give Feedback',
    helpAndSupport: 'Help and Support',
    aboutUs: 'About Us',
    confirmLogout: 'Confirm Logout',
    areYouSureLogout: 'Are you sure you want to log out?',
    cancel: 'Cancel',
    logOut: 'Log Out',
    feedbackTitle: 'Give Feedback',
    feedbackPlaceholder: 'Enter your feedback here...',
    close: 'Close',
    send: 'Send',
    contactUs: 'Contact Us',
    supportDescription: 'We are here to help and answer any question that you might have.',
    location: 'Park Avenue, Bangalore, 160010',
    phone: '+91-7887052000',
    email: 'contactus@gmail.com',
    locationIcon: '📍',
    phoneIcon: '📞',
    emailIcon: '✉️',
  },
  editProfile: {
    back: 'Back',
    title: 'Edit Profile',
    profilePicture: 'Profile Picture',
    addCustomPhoto: 'Add Custom Photo',
    details: 'Details',
    name: 'Name',
    namePlaceholder: 'Enter your name',
    height: 'Height (cm)',
    heightPlaceholder: 'Enter your height',
    weight: 'Weight (kg)',
    weightPlaceholder: 'Enter your weight',
    dailyMilestones: 'Daily Milestones',
    dailyCalories: 'Daily Calories',
    caloriePlaceholder: 'Set your daily calorie intake',
    dailyWater: 'Daily Water Intake',
    waterPlaceholder: 'Set your daily water intake',
    dailySteps: 'Daily Steps',
    stepsPlaceholder: 'Set your daily steps intake',
    goals: 'Goals',
    interests: 'Interests',
    gender: 'Gender',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    updatePassword: 'Update Password',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
  },
  aboutUs: {
    back: 'Back',
    missionStatement: '"Empowering Your Fitness Journey"',
    title: 'About Us',
    description: 'Welcome to our Fitness App, your ultimate companion for a healthier lifestyle! We are a passionate team dedicated to helping you achieve your fitness goals through personalized workouts, nutrition plans, and community support. Whether you\'re a beginner or a seasoned athlete, our app is designed to empower you on your wellness journey.',
    teamTitle: 'Meet Our Team',
    teamMember1Name: 'Jane Doe',
    teamMember1Role: 'Founder & Fitness Coach',
    teamMember2Name: 'John Smith',
    teamMember2Role: 'Nutrition Expert',
  },
  subscription: {
    back: 'Back',
    monthlyPrice: '$4.99/month',
    yearlyPrice: '$89.99/year',
    freeTrial: 'Free Trial',
    billingTitle: 'Recurring billing, cancel anytime',
    billingDescription: 'Contrary to what many people think, eating healthy is not easier said than done. Just a few good habits can make a great difference.',
    cancelSubscription: 'Cancel Subscription',
  },
};
  