export const lightTheme = {
  backgroundPrimary: '#F5F7FA',
  backgroundSecondary: '#FFF',
  backgroundTertiary: '#F9F9F9', 
  backgroundQuaternary: '#FFFFFF', 
  backgroundButtonPrimary: '#7A5FFF', 
  backgroundButtonSecondary: '#E0E0E0', 
  backgroundButtonDisabled: '#d3d3d3',
  backgroundBadge: '#F5F0FF', 
  backgroundActiveItem: '#f0f0f0',
  backgroundSuccess: '#C8F2C8',
  textPrimary: '#333', 
  textSecondary: '#666', 
  textError: 'red',
  textButtonPrimary: '#FFF',
  textButtonSecondary: '#7A5FFF', 
  textButtonTertiary: '#007AFF',
  textPlaceholder: '#999', 
  textAccent: '#7A5FFF', 
  textSuccess: 'green', 
  borderPrimary: '#E0E0E0', 
  borderSecondary: '#D3D3D3', 
  borderAccent: '#7A5FFF',
  borderTertiary: '#999', 
  shadow: '#000', 
  iconPrimary: '#333',
  iconSecondary: '#666',
  iconAccent: '#7A5FFF',
  iconLock: '#000', 
  switchTrackFalse: '#767577',
  switchTrackTrue: '#d2d2ff',
  switchThumbTrue: '#7A5FFF',
  switchThumbFalse: '#f4f3f4',
  activityIndicatorPrimary: '#b6b6b6',
  activityIndicatorSecondary: '#d0d0d0',
};

export const darkTheme = {
  backgroundPrimary: '#161616', 
  backgroundSecondary: '#030303', 
  backgroundTertiary: '#2e2e2e', 
  backgroundQuaternary: '#2e2e2e', 
  backgroundButtonPrimary: '#7A5FFF', 
  backgroundButtonSecondary: '#636363', 
  backgroundButtonDisabled: '#555',
  backgroundBadge: '#c4c3ff', 
  backgroundActiveItem: '#484848',
  backgroundSuccess: '#C8F2C8',
  textPrimary: '#dedede',
  textSecondary: '#bebebe',
  textError: 'red', 
  textButtonPrimary: '#FFF', 
  textButtonSecondary: '#7A5FFF', 
  textButtonTertiary: '#007AFF', 
  textPlaceholder: '#d3d3d3', 
  textAccent: '#7A5FFF', 
  textSuccess: 'green', 
  borderPrimary: '#444', 
  borderSecondary: '#444',
  borderAccent: '#7A5FFF',
  borderTertiary: '#444',
  shadow: '#000',
  iconPrimary: '#dedede',
  iconSecondary: '#666',
  iconAccent: '#7A5FFF', 
  iconLock: '#dedede', 
  switchTrackFalse: '#767577',
  switchTrackTrue: '#d2d2ff',
  switchThumbTrue: '#7A5FFF',
  switchThumbFalse: '#f4f3f4',
  activityIndicatorPrimary: '#b6b6b6', 
  activityIndicatorSecondary: '#d0d0d0', 
};

export type Theme = typeof lightTheme;

export const themes = {
  light: lightTheme,
  dark: darkTheme,
};